# Matrix operationer

In [1]:
import numpy as np

numpy dokumentation kan findes her https://numpy.org/doc/stable/index.html

In [2]:
my_first_matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
my_first_matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Transform matrix, ved at tilføje proberty T 

In [4]:
my_first_matrix.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

Bemærk at man ikke ændre værdien i det defineret objet, men kun outpttet af my_first_matrix, 

Skal output gemmes skal men tildele en ny variabel, 

In [15]:
my_second_matrix = my_first_matrix * 2

In [16]:
my_second_matrix

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

## Eksempel: Løsning af 2 ligninger med 2 ubekendte
1: 3x + 4y = 3 \
2: 4x - 5y = 3 \
Bemærk at matrisen skal skrives op rækkevis, dvs. [3x, 4y],[4x, 5y]

In [7]:
a = np.array([[3, 4], [4, 5]])
a

array([[3, 4],
       [4, 5]])

In [8]:
b = np.array([3, 3])
b

array([3, 3])

In [9]:
x = np.linalg.solve(a, b)
x

array([-3.,  3.])

## Eksempel: Løsning af 3 ligninger med 3 ubekendte
1: x + y + z = 5 \
2: 2x - y + z = 9 \
3: x - 2y + 3z = 16

In [10]:
a = np.array([[1, 1, 1], [2, -1, 1], [1, -2, 3]])
a

array([[ 1,  1,  1],
       [ 2, -1,  1],
       [ 1, -2,  3]])

In [11]:
b = np.array([5, 9, 16])
b

array([ 5,  9, 16])

In [12]:

x = np.linalg.solve(a, b)
x

array([ 2., -1.,  4.])

## Øvrige matris funktioner

Man kan lave en identity matrix med kommandoen eye("size")
The identity matrix of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Invers matrix laves me proberty I

In [14]:
my_first_matrix.I

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])